---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overseerr-mcp
  namespace: overseerr-mcp
spec:
  encryptedData:
    SEERR_API_KEY: AgA9gHRCkj80MXm3AREzEEq/YPJ72UUJmecHZdh/N5A2Rowz06Lk9zcy1DkHc7kWvLUG8tp72P3glpli8pleU7TLYyBciPBg1YlP4jbDvxxEdwWjXsl5eNL54vjemMr1Vk/3G/Tg0ysiBBoEVc3NgWNyL6MZvsHQ5ibwCyQ0SvXp4LfW05vi3OmlkAyPO08reTTwlG/0CUyoKGeOpRS7Xy36scNEHNwzvPPrI6y/qVoRNFx5NPfkD1TdsO/zuyWyEDFsG6kWYVMQRF8nTyaSQ9djzHG8/7In/olx9wDZag+eRMbXMqjEJ6Ht8yNaez4JTcHTd9057okER3iWsvvSJDdDL70ovMD78Yky/MfSXPGjp5QOJeANhfArkHt5Gdu7NrNUpoAyymv52EnK9zr81Onh9oE199d0LsQ9MVuR3PNGki7bjAuUn5mi+r+sg//MIVlp8jT5APV3H/KDDuOBRgHNM4Z/UO7uw95eIiH7FaNtW56v7r5fayDbG8IQdis34zg7/nzCgl4kFsZzPqO9rD63kVR67LXSVbMvaHPJuWs6cMglfQzHs13+kpl18ZcdY8ErMSatUDKPl/L36pvjcesX0smBBTsOiQxOAMQ7J7E/7zFthCvejKeuHTTNnsUcBtbNXxe855xc8ZqYYn9l54O/mVw023ULtkQDja7/HKF8w7pGK1zYie4pME14skLfljjnTvL6Pnui4x7H1sMQC5L4tAt+rOQBkXOpumFDm74Rs5GTWIS8VFCWGeEPiG/FP/dNuBUNK7UK5id2vxqH+tYGKEsS4w==
  template:
    metadata:
      name: overseerr-mcp
      namespace: overseerr-mcp
    type: Opaque
