---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: palworld-credentials
  namespace: games
spec:
  encryptedData:
    ADMIN_PASSWORD: AgAiR8MfEdKpn671hn0wepPCplpZyksmSOeUZVHbFXSpN/ZleWb+aeJBcqxjesjPvFh/TPnejY19JI6LL6Z3zFEYYgDPo/1hyw4NyEIAgLLpNGXuoxbiC5nHoEMOoHmw7unzX32lHrm1xwNTM4AeBIlkAF1NDviVFNofM8nmRL9+pbSURMlcig+VxM3L/JU97EcWSmqKR+k1h0ox3ONDT4JCW/4v7fuRNqWfub9XSpzksiSKh/uaP8fB6YwlT7DZvfHHgKjOB4BIu0WYfee98v5icMtsMBuEsFQ5W/Rx5f9Sjyq0OTZmkUS/xFLMaQH/+q6PBkJzk+NABknC9OX9i3cNVmYRDPDueR0dOF2ZJphqfBUbK5CrvZhCD0J5EByHsIMVI44QgQKQHk+1VkdwyliCWncuf/cTBkSt6poKvk533+AFUdnC+GKq6JO+KHct2btV4DeXa9d9/4P8qYk4JMc/TaR3kSQC9nQM2tgEK4V4se7w1r3F5A4nAvt2P/k+A/ZMPspMx8hAO7Hz7tcNWGOXzryU+QC850DrE7mmcsc8ebu2VNWpRxEAe4qWM1rvT24M7VgtbsBQ6z0hWxLm4vDdTrJoBBLtIi0eNoQroZt09bT+wLSYj4D1EnrOKr3yeLWqU402iVmvoPpIEBNQqviKxQ5ZxPF7jaRPcIang4zdkw4OXDQA9ZPMZY7dSapXMlvyHsIBvoHYeQ==
    SERVER_PASSWORD: AgA9ld0l3+b1ikQ9dajOmrE8heOTuUieR/9d9P7LWDEsRsehBqN1b6ATlYvbVNQFJcExhSG1s88BR8To15iEujbhGmSisFn/K0785pDkQOsuXoGS3jHa1MGihmnyay9wncS4TPJC8gxtmNVMLjz9DD/WRLscCX4bj44nflyhqnP6dn16E3nZTRJLJkPzdwVJELEWMHf+9KZvyBKdz/HFOIZ3v4CP/GYwVa5spWTMkI0OAf+xHYsRpXX+Q2doLosKXLnJQSO6XtbXaXJJxRS7ZgLiDWvF8iFI5eMT/+POnf7I5zVzoZV7rT0Z+BVIVopn1HVhMlds9JC251QnYzGqnnKdkGDMj+eF64LFrLCqQTrAgJeFipuZx5y1SopyMPvawB+UEnpVsmCr+AAAV1B/4sFljlrtJQTZEfn/xs0gzah2VSIJdyZ12D5EOI6o3wWElicFMwu5//b34vcBfrlWFWC/tri0tPVVKyqPpGXZ8U3jiZg1VytIsPabsPzhSq7l40y0IjoTdOsB1tb5t/uPtqbbR9usXLgo4YQGG3UmkWjWVwUDQnhqrdQpSIXdPhA5cR/MUXqJSW0/aD/VmBmYRDrlS7BamK7XGEc7NXe82VOR8Fh3AfIikl2ztqJ6LO8hZAnAE3uehnOlzRnNBFlCeqd5HWeYZCn9JdbpIH7/nlJyTVx6RmRI5di6Z8+fWbiVc3VYks36W03uUU+W
  template:
    metadata:
      name: palworld-credentials
      namespace: games
