server:
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "14Gi"

  storage:
    main:
      size: 30Gi
      storageClassName: longhorn

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.50.202"
    ports:
      - name: game
        port: 8211
        protocol: UDP
        targetPort: 8211
      - name: query
        port: 27015
        protocol: UDP
        targetPort: 27015
      - name: rcon
        port: 25575
        protocol: TCP
        targetPort: 25575

  config:
    puid: 1000
    pgid: 1000
    port: 8211
    query_port: 27015
    max_players: 10
    multithreading: true
    server_name: "Pokemon"
    server_description: "Gotta catch em all"
    timezone: "Australia/Sydney"
    public_ip: ""
    public_port: "8211"
    update_on_boot: true

    rcon:
      enable: true
      port: 25575
      externalPassword:
        name: palworld-credentials
        key: ADMIN_PASSWORD

    community:
      enable: false
      externalPassword:
        name: palworld-credentials
        key: SERVER_PASSWORD
