ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    hosts:
      - host: sonarr-k8s.home.lab
        path: /
        pathType: Prefix
persistence:
  nfs-downloads:
    enabled: true
    type: pvc
    existingClaim: nfs-downloads
    mountPath: /volume1/downloads