controllers:
  main:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/sonarr
          tag: 4.0.19.2997
          digest: sha256:8238c957aa2978bac57870ae5e035b81a62ae69e7257a53e721175ed3e306803
        env:
          TZ: "Australia/Sydney"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8989
              periodSeconds: 30
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8989
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8989
              periodSeconds: 5
              failureThreshold: 30

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

ingress:
  main:
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "200m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      cert-manager.io/cluster-issuer: homelab-ca-issuer
    tls:
      - secretName: sonarr-homelab-tls
        hosts:
          - sonarr.home.lab
    hosts:
      - host: sonarr.home.lab
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: longhorn
    globalMounts:
      - path: /config
  downloads:
    type: persistentVolumeClaim
    existingClaim: nfs-downloads
    globalMounts:
      - path: /downloads
  tv:
    type: persistentVolumeClaim
    existingClaim: nfs-tv-shows
    globalMounts:
      - path: /tv
