apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app: kometa
    app.kubernetes.io/instance: kometa
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: kometa
configMapGenerator:
  - name: kometa-config
    files:
      - config.yml
resources:
  - pvc.yaml
  - cronjob.yaml