apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  sources:
    - chart: homepage
      repoURL: https://jameswynn.github.io/helm-charts/
      targetRevision: 2.1.0
      helm:
        releaseName: homepage
        valueFiles:
          - $values/k8s/apps/homepage/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/apps/homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
