apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - chart: open-webui
      repoURL: https://helm.openwebui.com
      targetRevision: 16.6.0
      helm:
        releaseName: open-webui
        valueFiles:
          - $values/k8s/apps/open-webui/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
