apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr-mcp
  namespace: argocd
spec:
  project: default
  sources:
    - chart: app-template
      repoURL: oci://ghcr.io/bjw-s-labs/helm/app-template
      targetRevision: 5.2.1
      helm:
        releaseName: overseerr-mcp
        valueFiles:
          - $values/k8s/apps/overseerr-mcp/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/apps/overseerr-mcp
      directory:
        include: "{networkpolicy.yaml,sealedsecret.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: overseerr-mcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
