apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: palworld
  namespace: argocd
spec:
  project: default
  sources:
    - chart: palworld
      repoURL: https://twinki14.github.io/palworld-server-chart
      targetRevision: 2.7.1
      helm:
        releaseName: palworld
        valueFiles:
          - $values/k8s/apps/palworld/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/apps/palworld
  destination:
    server: https://kubernetes.default.svc
    namespace: games
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
