apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  sources:
    - chart: app-template
      repoURL: oci://ghcr.io/bjw-s-labs/helm/app-template
      targetRevision: 5.0.1
      helm:
        releaseName: prowlarr
        valueFiles:
          - $values/k8s/apps/prowlarr/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/apps/prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
