apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami.github.io/sealed-secrets
      targetRevision: 2.18.6
      helm:
        releaseName: helm-sealed-secrets
        valueFiles:
          - $values/k8s/admin/sealed-secrets/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/admin/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true
      enabled: true
