apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  sources:
    - chart: sonarr
      repoURL: oci://oci.trueforge.org/truecharts/sonarr
      targetRevision: 26.0.3
      helm:
        valueFiles:
          - $values/k8s/apps/sonarr/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/apps/sonarr
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarr
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true
      enabled: true