apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  project: default
  sources:
    - chart: tautulli
      repoURL: oci://oci.trueforge.org/truecharts/tautulli
      targetRevision: 22.5.0
      helm:
        valueFiles:
          - $values/k8s/apps/tautulli/values.yaml
    - repoURL: git@github.com:danjuv/homelab.git
      targetRevision: HEAD
      ref: values
      path: k8s/apps/tautulli
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true
      enabled: true