controllers:
  main:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/prowlarr
          tag: 2.3.6.5351
          digest: sha256:da6b1f914ad22778c347d554a59b6e40110f654b40528c8de516616382db5148
        env:
          TZ: "Australia/Sydney"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 9696
              periodSeconds: 30
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 9696
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 9696
              periodSeconds: 5
              failureThreshold: 30

service:
  main:
    controller: main
    ports:
      http:
        port: 9696

ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca-issuer
    tls:
      - secretName: prowlarr-homelab-tls
        hosts:
          - prowlarr.home.lab
    hosts:
      - host: prowlarr.home.lab
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
    globalMounts:
      - path: /config
