controllers:
  main:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.4.1.10545
          digest: sha256:260469d707617f4b5be1cd11a40be7e4889c63c5e7cdbc6a429626dc05863b6b
        env:
          TZ: "Australia/Sydney"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 7878
              periodSeconds: 30
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 7878
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 7878
              periodSeconds: 5
              failureThreshold: 30

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

ingress:
  main:
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "200m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      cert-manager.io/cluster-issuer: homelab-ca-issuer
    tls:
      - secretName: radarr-homelab-tls
        hosts:
          - radarr.home.lab
    hosts:
      - host: radarr.home.lab
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn
    globalMounts:
      - path: /config
  downloads:
    type: persistentVolumeClaim
    existingClaim: nfs-downloads
    globalMounts:
      - path: /downloads
  movies:
    type: persistentVolumeClaim
    existingClaim: nfs-movies
    globalMounts:
      - path: /movies
