---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: debitsuccess-credentials
  namespace: hermes
spec:
  encryptedData:
    password: AgBBQAjki/5vL4FVsExcoFskE1RlPITnGntBdVwsHEZu4BEc3ayzfl5DrylV3P+uP3CWyZKzNonXzS08NXwfodVmaWcahjoPfHCHuNzrkUbcqpE/zmCPoAFtjBDEsPKUWt+4hKUhjH4j9bqNFRthn4YvWHlYAt4Gx3+qaN8wfrkPca/9l4546onmwWv6h7CJSw2wDkQ091+RBsbPYHXyvBeSg9/KeOvDG4imcYAkfMyivNULOY0fQKBmd6elkWarr4/dvOjrvqlRLE3wDVdpMAh7gdJ4oO/3yfLqhHb5auomzbpxYT2lCMHBF4Aq+GQB5eY/aRX3ykW/GW0s0vpvG5Y9Wm1wmVEveJQMIjA9znHO1Px+TYmv/t7m/SvExTbLHoTsHU5suiq83bjsPmGyI6EgVuRc6xahstX12rkiXGCXSY51fW8ZLlyYVsCICYLCEw3cssHtEjgoM743ibrMi8IfB1pnPs3eVumqNE9FcneNrpZlqFLyhway6AExrcbaL4F5WrKnrE5LVXG4GtUcHCKxpAJJ7Um0881S8VM9afmF6hugNiedm/kCx7WQBP0d5ZE/Ns1Bmm53fajs/XBUbaOHwsO62ta+te1SY8Y29P0J7odGj+ek470pKUYpf2fpkbkS5rssRaCNABBcB5I81IHO5t/Ps3pY3T4HLKE8vMUZ7XLX4/tL6coWc/gQk+yS/Ee/UJTUR2niHXy3jJ0Vylm7Rgga
    username: AgA/VH8ZOV0HAUPod0SBjyOX1rf28VKfTv+aUtVb9ErTtVyGCt2DB3FYUQvIRRxQg1fRyODqMgVa6tI5QlAozExR8/WR/GtDTQ+BnRCoo8M4Io1piBrMH6Bhryc4HhlNRa7/3s5LsEgYx0LW+SCDasWoZ92cjFa95dbGRQ7eohlHlCnu88dko4wvSSs17vr9NVuZQdBvTRB4alcOdaaOR8SG6Sgqa1qZ9jw5w1F220fv646ClpHDJAY3u2FDc0FinF/1SJh0te1EAvAD2GEYqyDOrWWkarP56Ch1BU4EmeC8pcqTWpDRD/Q1fK/oWyn5Yyjy4bxPXhoXVwX6tWURraZNwk1o5K17twT8HCHp+Jhe/S1yO4kNappqO9mp+RgZldm9aTBTLwKDCUWi4fF/hLroRiQKGadi3mRt5bUU1dTWIcPjLsNFN6UhL1Vdzib7L6l8FwZNBW2pvsrCzteNCOd+2uugktJ0SFx6K02sI5KqbJt0kXE7j5tcSoDxJ6leLMLj8MIqwP1UdO7eYtn+xBZ7+wFnSBa/IS0fDjOZ2bpkY18CFi01PTgmiSzLxzqaoBPiEgPGqQHzuK2dYbIQ9TG4YJa6/TzoN5sKFDUH6LKqJAA7Q1yDH0xU59DJYikf5n6lGb1A2M+aQgCMLr54xgbtEA6QLa059Yzv6uN1N5Wh1nhIQdad6yPbhJLhDB+B6qsVwY+FF/0=
  template:
    metadata:
      name: debitsuccess-credentials
      namespace: hermes
    type: Opaque
