---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-mcp
  namespace: hermes
spec:
  encryptedData:
    GITHUB_MCP_TOKEN: AgC2dSNcwcI8JXh7Q7gOFhEfpDBZGGaofVDEdfwXKUtZVhHXvDKsNd4OseJpPIdzU+x1BJ1j1tf2XxzXVs7JS5KpwrNoEbLbOUnydbKgVnNVfA5e1S267t7Jloz1ihitDuEKOka5UqWhu62q8IuzNCswIkU3GimlGQtw9M5q/mMtspIjDFYt4DLpAxu2qxg+oIw/Tffp0xQ3XYOYYbJH3ZRL4nb4Fr8cd+keTg6oAiPZg9r17Z4xD8pR7NL0XMgjS60YFodq79kGetQ7tY75BF3+MP8Q8ZnGxCNFX3SebPlt8gahciKH+QceuTMfyOsWME64FtsoTm3uIx2iDjF0MUnqw7/JSch7ldwIaW8bJNURgeuJczxMNheXC+9qT/enpoRxIIyfiWBEAQTw+e9Svqph3v9N/F8SYk0v10w9y5n5KMS6Juj5lMphS9fO6W+vmfzux8yEoQeE722+AySWX+sahG+WAg5WexODresyIEtebrYfB+veOcJtTkXq96NwfyvTxgmPBLxYe4EiR3bC3DT0iAUnQW8J1adVj2HEzOQrFjhf9t4YJTKTXKA36X/xp8QBcN1UV6heth8de2oopflwm2qmC+TekGWemt2Vw0IZk4kesR4fkMCpDysSElCL1q/khp4trAWYFqofsTI/oZbJ7+7B/x+ALJ0HTokPkd3/Y/l+2TkwWvhswz7MsnQRk2r8o5xkFoq/VKtQd7b2WGMVoFPuD4+eni2Ik4OO0wddtAPpBneXq9Y1xwwUvsjzQkyRloUtYXQOfpyxaJcAQfe0CwkUEIUxrvCkrvbm6mNNddIbziW6z47ArjwWYdI=
    HINDSIGHT_API_KEY: AgCvZwEteSVdd7BzpG7kxQPlh5lcRVmn1USaIalEL7h9xRem+OyQ+zdMoe3F3xx81j/qnCc/nbTg3wdK6+47hPLpio+mYtmE4NO4sj43zrzYQYxRMiH8/ROC7eOa8mL1unvvGs78PbonyMmKAkrfWwWYW4tNSbg1EiCUpRuDbPe5GEs/BB2yM7awRgcxJUuxBKxFgy7lF0T63egKHiGVv1v/BokCObSPi3cCYatJg/R3IoyJAr8qLQCJf8DW5AU3IbJ3aYoEnYffR6HpkgaTa3fZECdApwAYwm81k3toipAdV5HvlK5uFFy5U9y4Q8OENAME5NzojbpJSgrnCtnflKIEU4AWSeM1v3H/N6bJzKN2eqlIOiBCJezXsjZiNwUIZR+puOJcZ0RoZVP40KBg7lU+tV+WdceB/f4/D/HXGGq8KlGQAvHpmUe4s/9JhbMc79jXIZ55Sp9UVzpnsTNeLPBbu+c4UM57nLIo/sxVhhSm+R3jflqmtRIE0KvVWZNARRECZ+G3DsiH1BmMDXCXwfhUR8L4f2BOMxbkVjVvCW6lDzvQb5dBkHbMOOgaDwL+MCqD3pDUebbvNhRTuYbg1Rov6NbaZGkZ0zz4Xc2fekPQjv85KAM568xlzn/3duEJwnCLR3kMHXl7/26c+7W7KUd5AAIuSpJ3dcZnQgAUDhwAVbma9RZfcbn06OsYf1n5ZA1Ts6y+tZ5ZlW6EEJy0PjIbCL5EQ8GASpsPudlmgp+FoECRdB9Sui4WxfLW6CapkIDHmrSK2THz6RGdXaN7km95
  template:
    metadata:
      name: hermes-mcp
      namespace: hermes
    type: Opaque
