apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-secrets
  namespace: hermes
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    API_SERVER_KEY: AgCu+wat8QR7AqGbA9h9yE+6xIi8hQ6EEeb+4lTOayBSz4gLoLYMa/2fDZKNa3VAnJ12yPS6EU2l6uXg8cWlFX38CXG5kWksyh5QjxRv9at72ThSVGLNTxLmdIPE2dFDWVPi6btU3tABr0V7FIui+GlmsM7vy/58VEGfg1+JPJvF/XKspS3xme8O8lPFFRJEwNl9MFbeLOwjn+7aNxrfvlx6yaf8SBPQnHyFwwdDS9Lr1twrocBbmdutYFZMxKLJX3tszzoceO/JD4wiOdlrwpAZaSeGp72/FEyo+O78+ZKdSNwfm9m6WUxtBEjMS9IpiOaFofOxUuBP1KQCE1TN7YTyvcgtwgcUouujC+KP6O6t5G+EyDbHH4KXo7uBgRqgmUmmXt3l+YVjW8LAqgHfzhobyGv5tD21xjOUaZKfPUBmvDv3nxdn+SYvVFfmE7livN0OCgx0+B9Eh49JIxJ46rKUyubvYuRWA6WH+2GnJVx4vlz6KStxdq26ynCHGmLA26lPDfdE2/eu1lrY2xQQUcrbnAmDcH1X4SoZIc3aCmxYIuxvuDzX3Ngrl8p30xMKOX4MsgTi+kEQelcQ7pJXsbsgQcxOgeLH8fT2kHk0gOLmMxot7zVv3bvtyCN6P8ppDtUAbyI2Wb8+T2ekgwwuBz3T8VbTqeqmnCmf9G2YwPOnHEcttUC3E3hpaWmYjBAo6/PnZs9DvgF/6FHpvEh3CB6/qJ8+WoPHNiMdEGt0DqRCBwud6nZzn2T4rfhxRgu1rbuDzNGbIZZKfTZdyvpvYrO0
  template:
    metadata:
      name: hermes-secrets
      namespace: hermes
