preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClassReplicaCount: 2
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
  tls: true
  tlsSecret: longhorn-homelab-tls
  host: longhorn.home.lab
  path: /
  pathType: Prefix