---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  encryptedData:
    password: AgCZ6ncu6Pik9StgNDOaSRnCVWIMbAn34gwQ91lc+KQjZJ7DGOJ6s2Uc1Wxx1mYqLANBx5Wz80ZSf98jsSKxab2KGGbrSN7m8R/kyG6CpiOZiCUHZX8h/r3oKcbzae7uM4fheJYwimf+gBrl3w4aIl8ImXYltc0N9kVkLEt9g5aCeCJerIANgDpVFSgPFRw6YnYbJ0txei7EWQvNH/+V9UAphUwwsSo5R46CK8aOxrxHkBxGQEtTR4eccI6RS82f1rEQK7KkI2OM2ozhkjwrjYzMvufUMNcHoe2WhbeZ4cza/78VVZlYlzvAPw5kNiJQ4SLO89OB4iBlBVZGFyJI9gcfdnvkT0XCj3BkoPP0lJ1Jg6rHiDCN6uso36tvuf4Po3PcNKVTCuZom+zuhqS5sfDyHIA2fO4NPgM6dwbLjb/TAtYq6WRrkuv2rNDB3ZZZZDxFBwMk45oaywbW+ARCnKAIW8w0DCwZ+vRXFbeZfpgNa0m14olJgyRJPjne3/OsbbkhLViwc+BThiEx0koUGNd7voTJ+2kIcAW1K8SOZDP4TIP26jSX5uQLzHOIt7OSYdJ1UcHfOSECxTwxl7k3GAlQHQAD+TnEgTISEg0CnpxBsrxBwt91FzCPv+vNV1eumq/8thuS3/VchmbJi5sQPwwj0T9wRnwckMC4Gl9viUBmaEYlQaI3UPYr+WQ5sjc0NRe4bEGlWeZzvA==
  template:
    metadata:
      name: external-dns-pihole
      namespace: external-dns
