apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: kometa-config
    behavior: merge
    files:
      - application.properties
resources:
  - ./../base/
  - sealedsecret.yaml
