apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kometa-secrets
  namespace: media
spec:
  encryptedData:
    PLEX_TOKEN: PLACEHOLDER
    TMDB_API_KEY: PLACEHOLDER
  template:
    metadata:
      name: kometa-secrets
      namespace: media
