apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-downloads-sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tv-shows
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-tv-shows-sonarr
