apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-movies
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tv-shows
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-tv-shows
