apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-downloads
    volumeAttributes:
      server: "192.168.50.80"
      share: "/volume1/downloads"
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-movies
    volumeAttributes:
      server: "192.168.50.80"
      share: "/volume1/movies"
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tv-shows
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-tv-shows
    volumeAttributes:
      server: "192.168.50.80"
      share: "/volume1/tv_shows"
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
