---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCwtB9w7899DsS4HCIf7lTCXipp7noH+My9Xulom2ed8t342ymc3qPAjSrCdIArauB7pqUhpbrQ2GSQrZcHlZ5c6AOnekTbPvMcQJE7RMMWHP3wzvVjR8VwPpkkEx5/xaQoddbSH7RMXn/ClVG5S9/kq/gAD19Ie4Qex1OZ5KZnlcvGRKhIs9n3d3RP2/0Eq0qx5aATVvYEl1SMD0jrjsDysPM/5ddR+CSb8LMcUGoYjPEu6ibNwKnC+9RodSEmIkXo4UF2pXK4ypQSSt7f4P+jZNyfwEOds3gcUXj5gqajvUrumV5vPlpnMHg+OE1apFe/FXoBtZ46/ue2KCZ3DDckmb+QRCPJ26qSwkVQb30o6CgUdPcL4ohNE5EdpYaeUbP9tyyRj03HUb8/1QOfnUJvZpiVJ8FKQhp6nng2+XmgefI2Pc6NHGR3YpM2kSiWoD2KKtxFU0EO1PLL+HO8C2+ANy7t0v5FtGvT4Z+zC5iwdbc15MGn3eI5+K7+uJikbARdErF4oNklr+Ez2dOI1eRjhiNMTr/W1IOp1L/Xt+/621fyd64Ary44qs38gxq8NVhJ6Pzzk9vTeQl/M/vlPTfw8XcV9Fos8SQxE2tCbzkiD77YU0d041dZsWEvBdIGynolcolwtXRUvGkn6PNu5XKDmo7yvCUMpkB/JmaYolVaQ4mYLkZrCgtMZsSRzg1abKCyJfhVFCtc2QXrQj9M2QbDtA==
    client_secret: AgBZ35RPGKajADj0Hvq3tpHIRRtMd5eEe2mx7rBGWFrrzQoSfXO7JNmAaSB1+VbN/yGJPrUb7bfDDbtuV1OXjinRKn062vU4bJtPxpnIHvV7ZxzXc0K9kC7+q9FtHi+TdzjAm9h1hfJ6Tk28fIwT6eJ+4lsOsnbHn2I5FNZY9VyJhANAVUsbn76Zkvy0n1OGgx2f46ol5RVFijEcxltLgkiYlc/zcYiqeahmL074Gjhf8GcRMvw4U1Wtlcv9wz9JA2D2y83gwG8khLd0DyByq224V40VIg37d+poEut3ZgisHztLrWHiVPQqMNMj08wHX3+nxt7nsc86byzc2jfZnYafSu/MJDVJnOIa5RbW+Ilt2BY1QcnUIkcB74JnlLAnllTXZacK3tCWFlDkRsHXHQOY8+ctDTXO2uitjRUxkV4Tw5+eTjaWnLN5Rw74QVx8xrDAo9+EHJM1j88gFYtYwuVAlWmmznwAsa8ELBXNAj8NNvq8DLtiMwtgDOikU0Kenm27wS508HPf9gOPh2i0Jg0aB8Q3DwKfKGWA5UVroDKZtsnAuG4rQkgf11uUiuGjzDVic82XfXfkaG5BsjMpTA7JIo5RnajjN+REL/r3oaUMuVcPWE6Aeepaaxsw5azFyLO4tLzKeMTF5pSHHpxDMLcPdqj2rONXEmuEves8W26Y7CGZxTbScMPhwEZFuCHOgU75f2rnKhmaJo2ALowZcHC4Pz4GEk1S36nYHOveOG6hMWQCiWb34tScqBlnVUS9eBIGBFY/Yw8Bjmry0EaYBQI=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
