ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: seer.home.lab
      paths:
        - path: /
          pathType: Prefix
config:
  persistence:
    size: 1Gi
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce

