ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
  tls:
    - secretName: overseerr-homelab-tls
      hosts:
        - overseerr.home.lab
  hosts:
    - host: overseerr.home.lab
      paths:
        - path: /
          pathType: Prefix
config:
  persistence:
    size: 3Gi
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce

